### PR TITLE
Replace lazy_static with once_cell

### PR DESCRIPTION
**Pull request by Lonami**
This should make it easier for the ecosystem to trim down the dependency tree.

I didn't update `rspec` to the `1.0` version because it seemed to pull a bunch other things and is only used in dev mode.

I think this is technically a breaking change, so let me know if we should bump the version number to 0.4.

### CODE REVIEW

**Comment by bb010g** [comment]
As long as `SHOULD_COLORIZE` is exposed to other crates, this is a breaking change.

**Comment by mackwic** [comment]
Hi I don't get why we should remove `lazy_static`,  would you develop the reasoning behind this PR?

Without good reason, I would prefer to do nothing and close this PR.

**Review by mackwic — CHANGES_REQUESTED** [review]
Please explain why we should do this change

**Comment by hwittenborn** [comment]
I do think `once_cell` has a cleaner API @mackwic (albeit not from the perspective of consumers of the library), but it probably would be a breaking change for any consumers of the API.

The only logic for it being a breaking change (from what I've seen) is that the static implements `LazyStatic`, but I'm not sure how big of a deal that is for you. Assuming this were to go through I'd probably make it a breaking change and likewise a major versoin bump (which I'd also prefer to avoid), but I'm fine with whatever. Just throwing it out as some thoughts.

**Comment by Lonami** [comment]
The ecosystem has been migrating from `lazy_static` to `once_cell`. [`once_cell` has been added to Rust's std](https://doc.rust-lang.org/std/cell/struct.OnceCell.html), which means that for newer versions of the compiler, the `once_cell` crate can compile to a mere re-export of std. But it's still useful to depend on it if we want to provide support for lower MSRV.

My main motivation as hinted in the PR description is keeping the dependency tree small where possible.

I don't know how important the `SHOULD_COLORIZE` constant really is. To be honest, I would personally replace it with a `fn`.

**Comment by hwittenborn** [comment]
Sorry to just now mention this @Lonami, but it looks like #119 is doing the same thing, and I'd probably accept that one just because the PR was made first.

If you'd want to make a PR for that `dev_dependencies` thing in `Cargo.toml` I'd be fine getting that merged in. Really sorry to not get this one in though.

**Comment by hwittenborn** [comment]
If you think this one merits enough to get merged in still I'd be fine reopening it though, just let me know.

**Comment by Lonami** [comment]
I was unaware the other PR existed. I had trouble running `cargo` when the TOML section was called `dev_dependencies` (underscore as opposed to dash). I also no longer see a need for the `extern crate once_cell` from the PR.

But ultimately I don't really care how it's done, as long as it gets merged eventually. I'll subscribe to the other PR instead.

**Comment by hwittenborn** [comment]
Yeah I'm not sure why the section in `Cargo.toml` was called `dev_dependencies` instead of `dev-dependencies`, I'm assuming it was from something an old version of Cargo handles things, but I'm not really sure honestly.

**Pull request closed without merging**
