### PR TITLE
Use a macro to declare all colorized colors

### PR DESCRIPTION
**Pull request by sameer**
Just simplifying this a bit.

I'm also preparing to implement #48, and it looks like we need a `ColorizedStr` since a String cannot be created in a const fn.

### CODE REVIEW

**Comment by SirWindfield** [comment]
Could this be expanded to include more colors like gray for example?

**Comment by sameer** [comment]
I think it would need to be a separate PR, gray is [not in the color enum](https://github.com/mackwic/colored/blob/master/src/color.rs#L6)

**Comment by SirWindfield** [comment]
I wonder what the decision was behind the colors. I expected all ANSI colors to be in there 🤔

**Comment by sameer** [comment]
Actually, maybe gray is already there.

https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit

"bright black" = gray, white = light gray, and bright white = white

**Comment by SirWindfield** [comment]
Maybe the nicknames should be put into a separate PR. But I like the idea :)

**Comment by rickygao** [comment]
I like this, cuz the same idea occurred to me while checking the source. Any plans on merging?

**Review by SirWindfield — APPROVED** [review]

**Comment by kurtlawrence** [comment]
Requiring `paste` dependency is not worth the gain in terseness.

**Pull request closed without merging**
