### PR TITLE
Update dev-dependency rspec

### PR DESCRIPTION
**Pull request by atezet**
While looking at the crate version I noticed this one is finally released (3 years ago), so figured I could bump this too. I kept the same format as the other dev dependencies for consistency.

### CODE REVIEW

**Review by spenserblack — APPROVED** [review]
Good catch! Perhaps we want to add a dependabot config :thinking:

**Review by spenserblack — CHANGES_REQUESTED** [review]
Oops, looks like usage needs to be updated. Yet again, I should have let CI run before submitting my review :sweat_smile:

**Comment by spenserblack** [comment]
:thinking: I should get around to adding a devcontainer config so contributors can work in a codespace.

**Comment by spenserblack** [comment]
You can also use a codespace if you'd prefer.

**Comment by atezet** [comment]
I'm not very familiar with codespace (haven't used it yet), but a dependabot config sounds like a good idea. Maybe the default setup is good enough?

**Comment by spenserblack** [comment]
Yeah the default config should be good enough. One common practice is to create a "dev dependency" group so they're updated in one PR, if you want to add that.

Codespaces are easy to use. It's basically VS Code running in the browser. You can also connect to the VM running on the cloud with a locally running IDE, but VS Code for the Web is the easiest to set up and what GitHub's site will do by default. You definitely don't have to use them to contribute, I'm just letting you know there are other options besides running tests locally. I'd be happy to answer any questions about them -- they're my favorite GH feature.

**Review by spenserblack — APPROVED** [review]

**Pull request merged**
