### PR TITLE
chore: replace atty with is-terminal

### PR DESCRIPTION
**Pull request by jcgruenhage**
`atty` is unmaintained and has a potential unaligned read. See https://github.com/rustsec/advisory-db/blob/main/crates/atty/RUSTSEC-2021-0145.md.

`is-terminal` is a replacement based on `atty`, with the soundness issue fixed and an (IMO) nicer to use API, mirroring what's available in the std lib on nightly with `std::io::IsTerminal`.

### CODE REVIEW

**Comment by faern** [comment]
Having this merged and released would be awesome. Is `colored` maintained?

**Comment by hwittenborn** [comment]
Thanks for the PR @jcgruenhage! This is being discussed at https://github.com/colored-rs/colored/issues/85#issuecomment-1616706636 as well, and it's the solution I'm wanting.

An MSRV just needs to be figured out before anything is done, depending on what the `fern` people decide. If they're fine with making the MSRV for this crate `1.70` [`std::io::IsTerminal`](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html) will end up being what's used, but if not the `is-terminal` crate will definitely be the next choice, at which point I'll go ahead and get this merged in.

**Comment by ChrisCA** [comment]
As a side note:
I wrote a [PR](https://github.com/borntyping/rust-simple_logger/pull/81) for simple_logger which also is a highly used dependent of colored. The PR replaced atty by the std implementation, however only for Windows users.
So for that crate, at least for Windows users, the MSRV is already 1.70. 
There is an issue open, targeting the atty security problem and I assume, crate users for simple_logger would welcome a fix for colored even so it bumps the MSRV for all users.

**Comment by hwittenborn** [comment]
I'm definitely on the route for using the stdlib implementation too @ChrisCA, I just got to figure out what the fern people are fine with. If I can get this crate down to having zero external dependencies it would definitely be really nice, we just got to make sure all the big consumers for this crate are fine with the high MSRV so no one gets any unexpected breakage.

**Comment by hwittenborn** [comment]
I'm terribly sorry about this @jcgruenhage, but I was in a bit of a Rust earlier getting `atty` out and I already had this change merged into the codebase.

Sadly that means there isn't really anything to merge in from this PR, but if you'd like to get another PR going I'd be more than glad to help! Let me know if there's anything I can do.

**Comment by jcgruenhage** [comment]
Don't worry. My goal of getting `atty` out of popular crates due to being unmaintained was still fulfilled ;)

**Pull request closed without merging**
